# Generated by Django 2.2 on 2019-04-20 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('IIN', models.CharField(max_length=300)),
                ('N_Id_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HelperRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2019, 4, 20, 15, 13, 40, 223004))),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=200)),
                ('IIN', models.CharField(max_length=300)),
                ('N_Id_number', models.CharField(max_length=200)),
            ],
        ),
    ]
